# Generated by Django 4.1.7 on 2023-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
